version: '3.4'

networks:
    backend:

services:
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
        - '8001:80'
    networks:
        - backend
    depends_on:
        - userdb
  userdb:
    image: postgres:16.0
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=userdb
    ports:
        - '5432:5432'
    volumes: 
        - ./UserService/userdb:/var/lib/postgresql/data
    networks:
        - backend

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
        - '8000:80'
    networks:
        - backend

